name: Java Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * 1'  # Her Pazartesi saat 08:00 (UTC)


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Set up Node.js (for Playwright CLI)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Playwright browsers
        run: |
          npm install -D playwright
          npx playwright install

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Archive Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReports
          path: test-output/

          
      - name: Send test report via email
      
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true 
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Java Playwright Test Raporu"
          from: ${{ secrets.EMAIL_USERNAME }}
          to: ${{ secrets.EMAIL_RECIPIENTS }}
         
          body: | 
             Hello Team,

             The Java Playwright test run has been completed. The report is attached.

             Best regards.
          attachments: test-output/ExtentReports.html
