name: Java Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Set up Node.js (for Playwright CLI)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Playwright browsers
        run: |
          npm install -D playwright
          npx playwright install

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Archive Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ExtentReports
          path: test-output/